### ISSUE TITLE
Excessive number of checkpoints when segment store is unavailable

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#102]
**Problem description**
In our internal testing, we have observed a connection leak that seems to be due to Pravega checkpointing. For context, the segment store was down (HDFS was full).

My assessment is the following. I have observed in the logs a stack trace like this repeatedly:

```
2018-01-19 15:26:00,234 WARN  org.apache.flink.runtime.checkpoint.CheckpointCoordinator     - Failed to trigger checkpoint 68610. (6 consecutive failed attempts so far)
java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at io.pravega.connectors.flink.ReaderCheckpointHook.lambda$triggerCheckpoint$0(ReaderCheckpointHook.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

This situation happens when we timeout in `ReaderCheckpointHook` after waiting too long. My *conjecture*  is that the connection leak is coming from the fact that the `ReaderGroup` instance is initiating the checkpointing, but not completing it, leaving the connection open. Assuming this is correct, I wonder if we should do one of the two:

1- Make checkpoints cancellable
2- Change `ReaderCheckpointHook` so that it throttles requests to checkpoints (I'm assuming we can't make changes to the checkpoint coordinator, but maybe that's a better approach) 

The segment store in Pravega being down is bad in itself, but we should avoid having the problem spilling to other parts.

For more detail, please check the log file:

[flink--mesos-appmaster.log.zip](https://github.com/pravega/flink-connectors/files/1647065/flink--mesos-appmaster.log.zip)

**Problem location**
Checkpoints, `ReeaderCheckpointHook`

**Suggestions for an improvement**
Figure out whether the conjecture make sense and fix the problem.

**Comment by EronWright** [comment]
Regarding (2), Flink's checkpoint coordinator already imposes a limit on concurrent checkpoints, a minimum time between checkpoints, and a timeout on the call to the hook (default: 10 mins).   

There's a coordinator-wide checkpoint lock that is kept while the hook executes, i.e. until the reader group checkpoint completes.   Our hook imposes a timeout (default: 5 seconds), which helps with cleanup and with ensuring a short timeout. 

Regarding (1), once our timeout fires and cancels the future, we should break out of the loop within `ReaderGroupImpl::initiateCheckpoint`.    Does that already happen?

**Comment by EronWright** [comment]
I opened a ticket to support cancellation in the loop future.
https://github.com/pravega/pravega/issues/2258

Looking at `ReaderGroupImpl::initiateCheckpoint`. this won't have a big effect because the loop probably crashes (with a suppressed exception) when the synchronizer is closed.

**Comment by tkaitchuck** [comment]
Canceling the future will have no effect on the upstream processing that is filling it. See the answers in: https://stackoverflow.com/questions/23320407/how-to-cancel-java-8-completable-future
We can't reasonably change that without changing to a different return value. The problem is that by being built in CompletableFutures are way more convenient than anything we could write, because everything already works with them.

**Comment by EronWright** [comment]
@tkaitchuck that's an over-generalization that doesn't hold here.   It is true that cancellation doesn't interrupt the thread, but in this scenario we're trying to cancel the loop that is driven by a scheduled timer.  To support cancellation, the loop logic should check the `isCancelled` state of the promise (in addition to the loop condition).

**Comment by fpj** [comment]
I don't think it is possible to actually cancel a checkpoint in the middle. It is a distributed mechanism, so once triggered, we need to let it finish. We might cancel the result, meaning that we don't care about it once it completes, but canceling the future does not really makes anything much better on the Pravega side as the checkpoint will keep going.

One option that we are contemplating to avoid having the Flink connector or any other application initiating an unbounded number of checkpoints without any of them completing is to throw an exception in the case there are too many checkpoints outstanding in a reader group. In the case the application has some threshold number of checkpoints outstanding, a new call to initiate checkpoint throws an exception.

Would this be a suitable solution to this problem?

**Comment by StephanEwen** [comment]
Can you help me understand this issue, to see if we can improve things on the Flink side?

As @EronWright mentioned, Flink should  not have more than N checkpoints going on concurrently (by default: 1). Only if that one fails or expires, another checkpoint is triggered.

What I think can happen is that if the checkpoint fails (exception from the reader group future), a new one is triggered. That way, many outstanding checkpoints pile up in Pravega.

Is that what you see happening?

**Comment by EronWright** [comment]
In the case that Pravega is incommunicado or slow to complete the checkpoint, the connector cancels the future and then initiates a new checkpoint later.  So I think that Flink is regulating the checkpoints nicely.    Meanwhile, Pravega could improve its handling of the cancellation signal (see pravega/pravega#2258).

**Comment by tkaitchuck** [comment]
Canceling the future and initiating a new one is not a good strategy. Because the readers will still perform the checkpoint even if there is nobody listening to the result, and if there are multiple checkpoints they are performed in order. So the policy of "If one CP is slow then start another" just results in a longer delay because the second CP cannot possibly finish before the first one.

**Comment by tkaitchuck** [comment]
Yes. We should make the reader throw if there are more than some number outstanding. If for no other reason that to protect the reader group. As we've seen blowing up the ReaderGroupState to be too large will bring down the reader group and is at present unrecoverable.

**Comment by EronWright** [comment]
Good point about not flooding the RG with checkpoints.   If we throw an exception during checkpoint initiation, Flink will try again at the next scheduled interval.  A potential downside is that the interval is user-defined and may be infrequent.   Another idea is, rather than throwing, we create a new checkpoint that subsumes any pending checkpoints.

Meanwhile the cancellation is still good to do, to cease polling for the status of that checkpoint.

**Comment by StephanEwen** [comment]
Having a limit in the reader group sounds good. Throwing a "reject exception" sounds also good - as mentioned by Eron before, this will mean the checkpoint is not taken and the next cycle will try again.

I am not sure if 'one' is the best default value for use with Flink, because even if Flink is set up for one checkpoint at a time (which it is by default), a savepoint can be concurrently triggered, meaning more than one checkpoint may be in flight. More than two concurrent checkpoints are rare, through.
