### ISSUE TITLE
FlinkPravegWriterITCase testExactlyOnceWriter fails randomly

### ISSUE THREAD

**Issue by hldnova** [pravega/flink-connectors#134]
**Problem description**
FlinkPravegaWriterITCase testExactlyOnceWriter seems to fail randomly. The failures were observed on master branch as of 5/15/2018. Executed **gradlew clean test** five times , it failed twice.

```
io.pravega.connectors.flink.FlinkPravegaWriterITCase > testExactlyOnceWriter FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.common.concurrent.Futures.lambda$await$0(Futures.java:68)
        at io.pravega.common.concurrent.Futures$$Lambda$945/194919.run(Unknown Source)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:90)
        at io.pravega.common.concurrent.Futures.await(Futures.java:66)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:144)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:119)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:104)
        at io.pravega.connectors.flink.FlinkPravegaWriterITCase.testExactlyOnceWriter(FlinkPravegaWriterITCase.java:219)
```

Looks like some of the parallel test(s) are consuming more resources and hence timeout is happening. 

**Problem location**
Connector system test code.

**Suggestions for an improvement**

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/238
