### ISSUE TITLE
Missing Netty shaded class

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#136]
**Problem description**
When I run the `WordCountWriter` sample, and it fails (for an unrelated reason), various stack traces eventually appear in the task manager log that suggest a shading problem:

```
java.lang.NoClassDefFoundError: io/pravega/shaded/io/netty/buffer/PoolArena$1
	at io.pravega.shaded.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:472)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:442)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:434)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:291)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:282)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache.free0(PoolThreadCache.java:256)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache.access$000(PoolThreadCache.java:39)
	at io.pravega.shaded.io.netty.buffer.PoolThreadCache$1.run(PoolThreadCache.java:126)
	at io.pravega.shaded.io.netty.util.ThreadDeathWatcher$Watcher.notifyWatchees(ThreadDeathWatcher.java:210)
	at io.pravega.shaded.io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:145)
	at io.pravega.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```
And:
```
May 16, 2018 8:58:17 PM io.pravega.shaded.io.grpc.internal.ChannelExecutor drain
WARNING: Runnable threw exception in ChannelExecutor
java.lang.NoClassDefFoundError: io/pravega/shaded/io/grpc/internal/ManagedChannelImpl$SubchannelImpl$1
	at io.pravega.shaded.io.grpc.internal.ManagedChannelImpl$SubchannelImpl.shutdown(ManagedChannelImpl.java:944)
	at io.pravega.shaded.io.grpc.util.RoundRobinLoadBalancerFactory$RoundRobinLoadBalancer.shutdown(RoundRobinLoadBalancerFactory.java:158)
	at io.pravega.shaded.io.grpc.internal.ManagedChannelImpl$IdleModeTimer.run(ManagedChannelImpl.java:275)
	at io.pravega.shaded.io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:72)
	at io.pravega.shaded.io.grpc.internal.ManagedChannelImpl$3.run(ManagedChannelImpl.java:347)
	at io.pravega.shaded.io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
	at io.pravega.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.pravega.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.pravega.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.pravega.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.pravega.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.pravega.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.pravega.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.pravega.shaded.io.grpc.internal.ManagedChannelImpl$SubchannelImpl$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:128)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

And
```
2018-05-17T00:12:28.8244037Z java.lang.NoClassDefFoundError: io/pravega/shaded/io/netty/util/collection/IntObjectHashMap$2
2018-05-17T00:12:28.824412Z 	at io.pravega.shaded.io.netty.util.collection.IntObjectHashMap.values(IntObjectHashMap.java:221)
2018-05-17T00:12:28.824415Z 	at io.pravega.shaded.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:355)
2018-05-17T00:12:28.8244175Z 	at io.pravega.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:322)
2018-05-17T00:12:28.82442Z 	at io.pravega.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
2018-05-17T00:12:28.8244224Z 	at io.pravega.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
2018-05-17T00:12:28.8244249Z 	at java.lang.Thread.run(Thread.java:748)
```
**Problem location**

**Suggestions for an improvement**

**Comment by EronWright** [comment]
I have been unable to repro the issue, closing for now.

**Comment by EronWright** [comment]
Related: #4401

**Comment by crazyzhou** [comment]
The requires not only the Pravega fixes aformentioned but also a Flink fix for https://issues.apache.org/jira/browse/FLINK-15467
