### ISSUE TITLE
Add Support for Flink 1.9

### ISSUE THREAD

**Issue by maddisondavid** [pravega/flink-connectors#260]
**Problem description**
Enable connector to support Flink 1.9 release. Here is the complete list of JIRAs that were addressed as part of Flink 1.9 release. (https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12315522&version=12344601)

**Problem location**
Build configurations, any relevant implementation classes with breaking API changes and integration/unit test cases

**Comment by crazyzhou** [comment]
Still got 2 test cases `io.pravega.connectors.flink.FlinkPravegaReaderRGStateITCase > testReaderState`  and `io.pravega.connectors.flink.FlinkPravegaTableITCase > testTableSourceUsingDescriptor` failed, both of them is failed by timeout and shows below error:

```
Aug 22, 2019 2:01:41 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=39, target=tls://localhost:32770} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:419)
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:182)
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:137)
	at io.pravega.client.admin.impl.ReaderGroupManagerImpl.<init>(ReaderGroupManagerImpl.java:65)
	at io.pravega.client.admin.ReaderGroupManager.withScope(ReaderGroupManager.java:46)
	at io.pravega.connectors.flink.FlinkPravegaReader.createReaderGroupManager(FlinkPravegaReader.java:439)
	at io.pravega.connectors.flink.FlinkPravegaReader.createReaderGroup(FlinkPravegaReader.java:429)
	at io.pravega.connectors.flink.FlinkPravegaReader.open(FlinkPravegaReader.java:225)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:529)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:393)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
```
