### ISSUE TITLE
fix npe when close pravega batch client factory in batch mode

### ISSUE THREAD

**Issue by chenlei677** [pravega/flink-connectors#635]
**Problem description**
Fix npe when close pravega batch client factory in batch mode
java.lang.NullPointerException
 at io.pravega.connectors.flink.FlinkPravegaInputFormat.close(FlinkPravegaInputFormat.java:178)
 at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:105)
 at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
 at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
 at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:263)
 Suppressed: java.lang.NullPointerException
  at io.pravega.connectors.flink.FlinkPravegaInputFormat.close(FlinkPravegaInputFormat.java:178)
  at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.close(InputFormatSourceFunction.java:120)
  at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:41)
  at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:797)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.runAndSuppressThrowable(StreamTask.java:776)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:691)
  at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cleanUpInvoke(SourceStreamTask.java:180)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:595)
  at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758)
  at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573)
  at java.lang.Thread.run(Thread.java:748)

**Problem location**
io.pravega.connectors.flink.FlinkPravegaInputFormat.close

**Suggestions for an improvement**

**Comment by chenlei677** [comment]
@crazyzhou Hello, I have created a new Issue, please help me to take a look. Thanks
