### ISSUE TITLE
Pravega Catalog fails when authentication required for SchemaRegistry access

### ISSUE THREAD

**Issue by maddisondavid** [pravega/flink-connectors#656]
**Problem description**
When running in an environment with a secure Schema Registry that requires authentication, the flink Job fails with the following exception:
```
io.pravega.schemaregistry.client.exceptions.RegistryExceptions$UnauthorizedException: User not authorized.
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.handleResponse(SchemaRegistryClientImpl.java:496)
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.lambda$getGroupProperties$6(SchemaRegistryClientImpl.java:194)
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:182)
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.withRetry(SchemaRegistryClientImpl.java:482)
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.getGroupProperties(SchemaRegistryClientImpl.java:186)
	at io.pravega.connectors.flink.formats.registry.PravegaRegistryRowDataDeserializationSchema.open(PravegaRegistryRowDataDeserializationSchema.java:147)
	at io.pravega.connectors.flink.dynamic.table.FlinkPravegaDynamicDeserializationSchema.open(FlinkPravegaDynamicDeserializationSchema.java:55)
	at io.pravega.connectors.flink.FlinkPravegaReader.open(FlinkPravegaReader.java:376)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:428)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:543)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:533)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:573)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Problem location**
When setting up the SchemaRegistry configuration, the `PravegaRegistryRowDataDeserializationSchema.open` method never sets the 
`.authentication(new PravegaCredentialProvider())` and therefore credentials are never added to the Schema Registry request.

**Suggestions for an improvement**
Add authentication method when setting up the SchemaRegistryClient to enable it to work in a secured environment.

**Comment by maddisondavid** [comment]
This looks like user error on my part that we need to document.  

Having the environment variable `pravega_client_auth_loadDynamic=true` set for the cluster environment loads the credential plugin.

However, that leads to the following error:
```
2022-02-22 18:44:19
javax.ws.rs.ProcessingException
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:305)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:643)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:641)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:414)
	at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:331)
	at com.sun.proxy.$Proxy44.getGroupProperties(Unknown Source)
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.lambda$getGroupProperties$6(SchemaRegistryClientImpl.java:187)
	at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:182)
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.withRetry(SchemaRegistryClientImpl.java:482)
	at io.pravega.schemaregistry.client.SchemaRegistryClientImpl.getGroupProperties(SchemaRegistryClientImpl.java:186)
	at io.pravega.connectors.flink.formats.registry.PravegaRegistryRowDataDeserializationSchema.open(PravegaRegistryRowDataDeserializationSchema.java:147)
	at io.pravega.connectors.flink.dynamic.table.FlinkPravegaDynamicDeserializationSchema.open(FlinkPravegaDynamicDeserializationSchema.java:55)
	at io.pravega.connectors.flink.FlinkPravegaReader.open(FlinkPravegaReader.java:376)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:428)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:543)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:533)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:573)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at io.pravega.schemaregistry.serializer.shared.credentials.PravegaCredentialProvider.getMethod(PravegaCredentialProvider.java:39)
	at io.pravega.schemaregistry.client.AuthFilter.filter(AuthFilter.java:31)
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:143)
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:131)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)
	... 26 more
```

**Comment by maddisondavid** [comment]
I THINK the above issue might be caused by using the wrong method when setting up the `PravegaCredentialsProvider`. If we use the first method, it expects the credentials to already be in the Pravega configuration, but the second method will trigger collection of the credentials from something like Keycloak.
```
    public PravegaCredentialProvider(ClientConfig pravegaClientConfig) {
        this.credentials = pravegaClientConfig.getCredentials();
    }

    public PravegaCredentialProvider() {
        credentials = ClientConfig.builder().build().getCredentials();
    }
```

**Comment by fyang86** [comment]
The PR has been raised for this issue. This is the same issue as #539 , but we didn't fix it in the related PR though.

**Comment by crazyzhou** [comment]
The `pravegaConfig.getClientConfig` is also triggering the `build()` of the `clientConfig`, so the credential loading should be fine. Confirmed that it is a user issue
